language: objective-c
osx_image: xcode9.3

xcode_sdk:
- iphonesimulator11.3


jobs:
  include:
    - script: xcodebuild -workspace FlightAnimator.xcworkspace -scheme FlightAnimator-Demo -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=11.3' test
